### ISSUE TITLE
Information about requirements and dependencies. Particularly xnor_matmul.so.

### ISSUE THREAD

**Issue by Sreerag-ibtl** [ivanbergonzani/binarized-neural-network#3]
My environment : Google colab.
TensorFlow version used : 
1.15.0
My work flow : 
 1. Cloned the repo.
 2. Executed python train.py. 
Issue:
 When tried to execute python xnor_test.py, below error occured
`Traceback (most recent call last):
  File "xnor_test.py", line 15, in <module>
    xnor_matmul_module = tf.load_op_library('./xnor_matmul/xnor_matmul.so')
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: ./xnor_matmul/xnor_matmul.so: cannot open shared object file: No such file or directory`
My effort to solve this : 
 Tried to generate .so file by first converting .cc file to .o and then to .so. But compiling 
 xnor_matmul.cc resulted in the following error:
`xnor_matmul/xnor_matmul.cc:1:10: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.`
Is there anything I am missing?

**Comment by abidalrekab** [comment]
I have the same issue! the author isn't responding!
